apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo
spec:
  selector:
    matchLabels:
      name: django-todo
    template:
      metadata:
        name: django-todo
      spec:
       containers:
         name: django-todo
         image: 224574/django-todo:jatest
         env:
         - name: POSTGRES_HOST
           value: postgres
         - name: POSTGRES_DB
           valueFrom:
            secretKeyRef:
              name: postgress-secret
              key: POSTGRES_DB
         - name: POSTGRES_USER
           valueFrom:
            secretKeyRef:
              name: postgress-secret
              key: POSTGRES_USER
         - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgress-secret
                key: POSTGRES_PASSWORD
       ports:
        - containerPort: 8000

           


